name: test

on:
  pull_request:
    branches: [ main ]


jobs:
  coverage:

    runs-on: ubuntu-latest
    
    steps:
    - name: Test with pytest
      run: |
        mkdir -p ${{ github.workspace }}/data/test
        chmod 777 -R ${{ github.workspace }}/data/test
        coverage run -m --source=source/ pytest test/
        coverage xml
      
    - name: Get Cover 
      uses: orgoro/coverage@v3
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}

